# Generated by Django 3.2.21 on 2023-09-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.CharField(default='InProgress', max_length=100),
        ),
    ]
